### ISSUE TITLE
Attempting to update

### ISSUE THREAD

**Issue by ericedson98** [notpeelz/github-create-release#29]
Currently receiving the following error while using this action. The tag has been deleted at this point.

checking if tag already exists
attempting to update existing tag
Error: failed to update existing tag
HttpError: Reference does not exist
    at file:///D:/a/_actions/notpeelz/action-gh-create-release/v5.0.1/action.mjs:4785:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (file:///D:/a/_actions/notpeelz/action-gh-create-release/v5.0.1/action.mjs:26918:9)
    at async file:///D:/a/_actions/notpeelz/action-gh-create-release/v5.0.1/action.mjs:27074:3

**Comment by notpeelz** [comment]
Could you share the workflow file?

**Comment by ericedson98** [comment]
The workflow file is pretty large and has some private information in it.
I can share this with you, the tag is deleted in the step prior.

```
Run dev-drprasad/delete-tag-and-release@v0.2.1
📕  given repo is "organization-xyz/repository-xyz"
🏷  given tag is "latest-beta"
🍻  found 1 releases to delete
👍🏼  all releases deleted successfully!
✅  tag "latest-beta" deleted successfully!
```

Also here is the snippet of the workflow file that utilizes this action.

```
- name: release-beta
        uses: notpeelz/action-gh-create-release@v5.0.1
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          title: 🩸Bleeding Edge🩸
          body: patch-notes.md
          body-source: file
          strategy: replace
          prerelease: true
          draft: false
          files: ${{ github.workspace }}\XYZupdate.zip
          tag: 'latest-beta'
          target: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by notpeelz** [comment]
The `replace` strategy checks if the tag already exists before attempting to replace it. I'm guessing GitHub's REST API isn't 100% atomic, which is why you're seeing this error.
Is there a reason you're deleting the tag/release in a separate step before creating the release? github-create-release should handle this for you.

If possible, could you also share the workflow triggers and the `dev-drprasad/delete-tag-and-release` step (for reproduction)?

**Comment by ericedson98** [comment]
To be honest, I can't remember why we are deleting the tag in a separate step (Probably because we ran into some sort of issue without it). I am going to remove the previous step and attempt  to run the workflow to confirm.
Also for reproduction, here is the prior step.
```
- uses: dev-drprasad/delete-tag-and-release@v0.2.1
        name: delete-beta-tag
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          delete_release: true # default: false
          tag_name: 'latest-beta' # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
